server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/**
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post/**
